# Generated by Django 4.1.1 on 2022-10-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("won", "Korean Won"), ("dollar", "US dollar")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("kr", "Korea"), ("en", "English")],
                max_length=2,
                null=True,
            ),
        ),
    ]
